import { expect, test } from '@playwright/test'

test.use({ permissions: ['clipboard-read', 'clipboard-write'] })

test('persists a solved dynamic recipe and marks it stale after profile changes', async ({ page }) => {
  test.setTimeout(120_000)
  await page.goto('/')

  await expect(
    page.getByRole('heading', { name: 'FF14 月面工程小工具' }),
  ).toBeVisible()
  await expect(page.getByTestId('profile-panel')).toBeVisible()
  await expect(page.getByTestId('workbench-sidebar').getByTestId('profile-panel')).toBeVisible()
  await expect(page.getByTestId('profile-panel')).toHaveAttribute('open', '')
  await page.getByLabel('配裝名稱').fill('遊戲畫面')
  await page.getByLabel('職業等級', { exact: true }).fill('79')
  await page.getByLabel('作業精度').fill('1555')
  await page.getByLabel('加工精度').fill('1534')
  await page.getByLabel('CP').fill('421')
  await page.getByTestId('save-profile').click()
  await expect(page.getByText('配裝已保存。')).toBeVisible()
  await page.getByTestId('profile-summary').click()
  await expect(page.getByTestId('profile-panel')).not.toHaveAttribute('open', '')
  await expect(page.getByTestId('profile-summary')).toContainText('目前等級 Lv.79')
  await expect(page.getByLabel('配裝名稱')).toBeHidden()
  await page.getByTestId('profile-summary').click()
  await expect(page.getByLabel('配裝名稱')).toBeVisible()

  await page.getByTestId('recipe-search').fill('宇宙探索用的紡車')
  await page.locator('.search-results button', { hasText: 'ID 36173' }).click()
  await expect(page.getByTestId('recipe-level')).toHaveValue('79')
  await expect(page.getByText('動態配方', { exact: true })).toBeVisible()
  await expect(page.getByText('1197', { exact: true })).toBeVisible()
  await expect(page.getByText('2790', { exact: true })).toBeVisible()
  await expect(page.getByLabel('我已學會「掌握」')).not.toBeChecked()

  await page.getByTestId('solve-recipe').click()
  await expect(page.getByTestId('solve-status')).toHaveText('求解與同版本模擬驗證完成。', {
    timeout: 120_000,
  })
  await expect(page.getByTestId('solution-result')).toContainText('與目前設定一致')
  await expect(page.getByTestId('solution-result')).toContainText('製作完成')
  await expect(page.getByTestId('solution-result')).toContainText('品質目標達成')
  await expect(page.getByTestId('solution-result')).toContainText('可靠／最壞狀況')
  await expect(page.getByTestId('solution-result')).toContainText('剩餘 CP')
  await expect(page.locator('.macro-card pre').first()).not.toContainText('/ac 掌握 <wait.2>')
  await expect(page.locator('.macro-card pre').first()).toContainText('/echo 巨集 #1 已完成！')
  await expect(page.locator('.macro-card pre').first()).not.toContainText('/mlock')
  await page.getByLabel('巨集加入 /mlock（預設關閉）').check()
  await expect(page.locator('.macro-card pre').first()).toContainText('/mlock')
  await page.getByTestId('copy-section-1').click()
  await expect(page.getByTestId('copy-section-1')).toHaveText('已複製')
  const firstMacro = await page.locator('.macro-card pre').first().textContent()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(firstMacro)
  await page.locator('.macro-card pre').first().click()
  await expect(page.getByTestId('copy-section-1')).toHaveText('已複製')
  await expect(page.getByTestId('copy-section-1')).toHaveText('複製此段', { timeout: 3_000 })
  await page.getByTestId('copy-section-1').click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(firstMacro)
  await expect(page.getByRole('button', { name: /全部複製/ })).toHaveCount(0)

  await page.reload()
  await expect(page.getByTestId('solution-result')).toContainText('Lv.79 解答')
  await expect(page.getByLabel('巨集加入 /mlock（預設關閉）')).toBeChecked()
  await expect(page.locator('.macro-card pre').first()).toContainText('/mlock')
  await expect(page.getByTestId('action-sequence')).not.toContainText('掌握')
  await expect(page.getByTestId('action-sequence')).toContainText('坯料製作')
  await expect(page.locator('.saved-recipes > li')).toHaveCount(1)

  await page.getByRole('button', { name: '新增配裝' }).click()
  await page.getByLabel('配裝名稱').fill('備用配裝')
  await page.getByLabel('職業等級', { exact: true }).fill('79')
  await page.getByLabel('作業精度').fill('1600')
  await page.getByLabel('加工精度').fill('1534')
  await page.getByLabel('CP').fill('421')
  await page.getByTestId('save-profile').click()
  await expect(page.getByTestId('solution-result')).toContainText('使用舊能力值／選項求解')

  await page.getByTestId('profile-select').selectOption({ label: '遊戲畫面 · Lv.79' })
  await expect(page.getByTestId('solution-result')).toContainText('與目前設定一致')

  await page.getByLabel('作業精度').fill('1556')
  await page.getByTestId('save-profile').click()
  await expect(page.getByTestId('solution-result')).toContainText('使用舊能力值／選項求解')

  await page.getByTestId('recipe-level').fill('80')
  await page.getByTestId('recipe-level').press('Tab')
  await expect(page.getByTestId('solution-result')).toHaveCount(0)
  await expect(page.getByTestId('solution-history')).toContainText('Lv.79')
  await page.getByTestId('solve-recipe').click()
  await expect(page.getByTestId('solve-status')).toContainText('請選擇同為 Lv.80 的配裝')
  await expect(page.getByText(/最近求解失敗：.*Lv.80/)).toBeVisible()
  await page.getByTestId('recipe-level').fill('79')
  await page.getByTestId('recipe-level').press('Tab')
  await expect(page.getByTestId('solution-result')).toContainText('Lv.79 解答')

  await page.getByLabel('可靠／最壞狀況求解').uncheck()
  await page.getByTestId('solve-recipe').click()
  await expect(page.getByTestId('solve-status')).toHaveText('求解與同版本模擬驗證完成。', {
    timeout: 120_000,
  })
  await expect(page.getByTestId('solution-result')).toContainText('非保證解答')
  await expect(page.getByText(/此解答未使用可靠／最壞狀況模式/)).toBeVisible()

  await page.getByRole('button', { name: /裁衣/ }).click()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(0)
  await page.getByRole('button', { name: /木工/ }).click()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(1)

  page.once('dialog', (dialog) => dialog.accept())
  await page.getByTestId('clear-all').click()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(0)
})
