import { expect, test } from '@playwright/test'

test.use({ permissions: ['clipboard-read', 'clipboard-write'] })

test('keeps stable query history, batch-retains recipes, and shares one job level', async ({ page }) => {
  await page.goto('/')

  await page.getByTestId('job-level-summary').fill('79')
  await page.getByTestId('job-level-summary').press('Tab')
  await page.getByTestId('recipe-search').fill('宇宙探索用的紡車')
  await page.locator('.search-results button', { hasText: 'ID 36173' }).click()
  await page.getByTestId('recipe-search').fill('宇宙探索用的樹液')
  await page.locator('.search-results button', { hasText: 'ID 36178' }).click()

  const historyNames = page.locator('.history-recipes .saved-recipe-open strong')
  await expect(historyNames).toHaveText(['宇宙探索用的紡車', '宇宙探索用的樹液'])
  await page.locator('.history-recipes .saved-recipe-open').first().click()
  await expect(historyNames).toHaveText(['宇宙探索用的紡車', '宇宙探索用的樹液'])

  await page.getByRole('button', { name: '全選' }).click()
  await page.getByRole('button', { name: '加入保留清單（2）' }).click()
  await page.getByTestId('retained-tab').click()
  await expect(page.locator('.retained-recipes .saved-recipe-open strong')).toHaveText([
    '宇宙探索用的紡車',
    '宇宙探索用的樹液',
  ])

  await page.getByTestId('history-tab').click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByTestId('clear-history').click()
  await expect(page.getByTestId('history-list-panel')).toContainText('首次查詢順序')
  await page.getByTestId('retained-tab').click()
  await expect(page.locator('.retained-recipes > li')).toHaveCount(2)

  await page.locator('.retained-recipes .saved-recipe-open').first().click()
  await expect(page.getByTestId('recipe-level')).toHaveValue('79')
  await page.getByTestId('recipe-level').fill('80')
  await page.getByTestId('recipe-level').press('Tab')
  await expect(page.getByTestId('job-level-summary')).toHaveValue('80')
  await expect(page.getByTestId('current-solution-status')).toContainText('Lv.80 尚無解答')

  await page.reload()
  await expect(page.getByTestId('job-level-summary')).toHaveValue('80')
  await page.getByTestId('retained-tab').click()
  await expect(page.locator('.retained-recipes > li')).toHaveCount(2)
})

test('calculates and persists initial quality from HQ ingredients', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /鍛鐵/ }).click()
  await page.getByTestId('recipe-search').fill('白鋼彎刃刀')
  await page.locator('.search-results button', { hasText: 'ID 111' }).click()
  await page.getByTestId('solver-options-summary').click()

  await expect(page.getByLabel('依 HQ 素材計算')).toBeChecked()
  await expect(page.getByTestId('initial-quality')).toHaveValue('0')
  await expect(page.getByTestId('initial-quality')).toHaveAttribute('readonly', '')

  await page.getByTestId('hq-ingredient-0').fill('1')
  await page.getByTestId('hq-ingredient-0').press('Tab')
  await expect(page.getByTestId('initial-quality')).toHaveValue('109')

  await page.getByTestId('hq-ingredient-0').fill('0')
  await page.getByTestId('hq-ingredient-2').fill('1')
  await page.getByTestId('hq-ingredient-2').press('Tab')
  await expect(page.getByTestId('initial-quality')).toHaveValue('126')

  await page.getByTestId('hq-ingredient-0').fill('2')
  await page.getByTestId('hq-ingredient-1').fill('1')
  await page.getByTestId('hq-ingredient-1').press('Tab')
  await expect(page.getByTestId('initial-quality')).toHaveValue('450')

  await page.reload()
  await page.getByRole('button', { name: /鍛鐵/ }).click()
  await page.getByTestId('solver-options-summary').click()
  await expect(page.getByLabel('依 HQ 素材計算')).toBeChecked()
  await expect(page.getByTestId('hq-ingredient-0')).toHaveValue('2')
  await expect(page.getByTestId('hq-ingredient-1')).toHaveValue('1')
  await expect(page.getByTestId('hq-ingredient-2')).toHaveValue('1')
  await expect(page.getByTestId('initial-quality')).toHaveValue('450')
})

test('persists a solved dynamic recipe and marks it stale after profile changes', async ({ page }) => {
  test.setTimeout(120_000)
  await page.goto('/')

  await expect(
    page.getByRole('heading', { name: 'FF14 月面工程小工具' }),
  ).toBeVisible()
  await expect(page.getByTestId('profile-panel')).toBeVisible()
  await expect(page.getByTestId('workbench-sidebar').getByTestId('profile-panel')).toBeVisible()
  await expect(page.getByTestId('profile-panel')).toHaveAttribute('open', '')
  await page.getByLabel('配裝名稱').fill('遊戲畫面')
  await page.getByLabel('職業等級', { exact: true }).fill('79')
  await page.getByLabel('作業精度').fill('1555')
  await page.getByLabel('加工精度').fill('1534')
  await page.getByLabel('CP').fill('421')
  await page.getByTestId('save-profile').click()
  await expect(page.getByText('配裝已保存。')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('profile-panel')).not.toHaveAttribute('open', '')
  await expect(page.getByTestId('job-level-summary')).toHaveValue('79')
  await expect(page.getByLabel('配裝名稱')).toBeHidden()
  await page.getByTestId('profile-summary').getByRole('heading', { name: '配裝' }).click()
  await expect(page.getByLabel('配裝名稱')).toBeVisible()

  await page.getByTestId('recipe-search').fill('宇宙探索用的紡車')
  await page.locator('.search-results button', { hasText: 'ID 36173' }).click()
  await expect(page.getByTestId('recipe-level')).toHaveValue('79')
  await expect(page.getByText('動態配方', { exact: true })).toBeVisible()
  await expect(page.getByText('1197', { exact: true })).toBeVisible()
  await expect(page.getByText('2790', { exact: true })).toBeVisible()
  await page.getByTestId('solver-options-summary').click()
  await expect(page.getByTestId('solver-options-panel')).toContainText('品質目標')
  await expect(page.getByTestId('solver-options-panel')).toContainText('可用技能')
  await expect(page.getByTestId('solver-options-panel')).toContainText('求解策略與巨集')
  await expect(page.getByTestId('initial-quality')).toHaveValue('0')
  await page.getByTestId('initial-quality').fill('900')
  await page.getByTestId('initial-quality').press('Tab')
  await expect(page.getByLabel('可靠／最壞狀況求解')).not.toBeChecked()
  await expect(page.getByLabel('我已學會「掌握」')).not.toBeChecked()
  await page.getByTestId('solver-options-summary').click()

  await page.getByTestId('solve-recipe').click()
  await expect(page.getByTestId('solve-status')).toHaveText('求解與同版本模擬驗證完成。', {
    timeout: 120_000,
  })
  await expect(page.getByTestId('solution-result')).toContainText('解答已更新')
  await expect(page.getByTestId('solution-result')).toContainText('製作完成')
  await expect(page.getByTestId('solution-result')).toContainText('品質目標達成')
  await expect(page.getByTestId('solution-result')).toContainText('初期品質900')
  await expect(page.getByTestId('solution-result')).toContainText('非保證解答')
  await expect(page.getByText(/此解答未使用可靠／最壞狀況模式/)).toBeVisible()
  await expect(page.getByTestId('solution-result')).toContainText('剩餘 CP')
  await expect(page.locator('.macro-card pre').first()).not.toContainText('/ac 掌握 <wait.2>')
  await expect(page.locator('.macro-card pre').first()).toContainText('/echo 巨集 #1 已完成！')
  await expect(page.locator('.macro-card pre').first()).not.toContainText('/mlock')
  await expect(page.getByTestId('solver-options-panel')).not.toHaveAttribute('open', '')
  const macroViewport = await page.locator('.macro-card').first().evaluate((element) => ({
    top: Math.round(element.getBoundingClientRect().top),
    viewportHeight: window.innerHeight,
  }))
  expect(macroViewport.top).toBeGreaterThanOrEqual(0)
  expect(macroViewport.top).toBeLessThan(macroViewport.viewportHeight - 80)
  await page.getByTestId('solver-options-summary').click()
  await page.getByTestId('initial-quality').fill('901')
  await page.getByTestId('initial-quality').press('Tab')
  await expect(page.getByTestId('solution-result')).toContainText('解答未更新')
  await page.getByTestId('initial-quality').fill('900')
  await page.getByTestId('initial-quality').press('Tab')
  await expect(page.getByTestId('solution-result')).toContainText('解答已更新')
  await page.getByLabel('巨集加入 /mlock（預設關閉）').check()
  await expect(page.locator('.macro-card pre').first()).toContainText('/mlock')
  await page.getByTestId('copy-section-1').click()
  await expect(page.getByTestId('copy-section-1')).toHaveText('已複製')
  const firstMacro = await page.locator('.macro-card pre').first().textContent()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(firstMacro)
  await page.locator('.macro-card pre').first().click()
  await expect(page.getByTestId('copy-section-1')).toHaveText('已複製')
  await expect(page.getByTestId('copy-section-1')).toHaveText('複製此段', { timeout: 3_000 })
  await page.getByTestId('copy-section-1').click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(firstMacro)
  await expect(page.getByRole('button', { name: /全部複製/ })).toHaveCount(0)

  await page.reload()
  await expect(page.getByTestId('solution-result')).toContainText('Lv.79 解答')
  await expect(page.getByTestId('initial-quality')).toHaveValue('900')
  await expect(page.getByLabel('巨集加入 /mlock（預設關閉）')).toBeChecked()
  await expect(page.locator('.macro-card pre').first()).toContainText('/mlock')
  await expect(page.getByTestId('action-sequence')).not.toContainText('掌握')
  await expect(page.getByTestId('action-sequence')).toContainText('坯料製作')
  await expect(page.locator('.saved-recipes > li')).toHaveCount(1)
  await expect(page.getByTestId('profile-panel')).not.toHaveAttribute('open', '')

  await page.getByTestId('profile-summary').getByRole('heading', { name: '配裝' }).click()
  await page.getByRole('button', { name: '新增配裝' }).click()
  await page.getByLabel('配裝名稱').fill('備用配裝')
  await page.getByLabel('職業等級', { exact: true }).fill('79')
  await page.getByLabel('作業精度').fill('1600')
  await page.getByLabel('加工精度').fill('1534')
  await page.getByLabel('CP').fill('421')
  await page.getByTestId('save-profile').click()
  await expect(page.getByTestId('solution-result')).toContainText('解答未更新')

  await page.getByTestId('profile-select').selectOption({ label: '遊戲畫面 · Lv.79' })
  await expect(page.getByTestId('solution-result')).toContainText('解答已更新')

  await page.getByLabel('作業精度').fill('1556')
  await page.getByTestId('save-profile').click()
  await expect(page.getByTestId('solution-result')).toContainText('解答未更新')

  await page.getByTestId('recipe-level').fill('80')
  await page.getByTestId('recipe-level').press('Tab')
  await expect(page.getByTestId('solution-result')).toHaveCount(0)
  await expect(page.getByTestId('solution-history')).toContainText('Lv.79')
  await page.getByTestId('solve-recipe').click()
  await expect(page.getByTestId('solve-status')).toContainText('尚未設定木工師 Lv.80 配裝')
  await expect(page.getByText(/最近求解失敗：.*Lv.80/)).toBeVisible()
  await page.getByRole('button', { name: '以目前能力值建立同等級配裝' }).click()
  await expect(page.getByTestId('missing-level-profile')).toHaveCount(0)
  await expect(page.getByTestId('profile-select')).toHaveValue(/.+/)
  await page.getByTestId('recipe-level').fill('79')
  await page.getByTestId('recipe-level').press('Tab')
  await expect(page.getByTestId('solution-result')).toContainText('Lv.79 解答')

  await page.getByTestId('solver-options-summary').click()
  await page.getByLabel('可靠／最壞狀況求解').check()
  await page.getByTestId('solve-recipe').click()
  await expect(page.getByTestId('solve-status')).toHaveText('求解與同版本模擬驗證完成。', {
    timeout: 120_000,
  })
  await expect(page.getByTestId('solution-result')).toContainText('可靠／最壞狀況')
  await expect(page.getByText(/此解答未使用可靠／最壞狀況模式/)).toHaveCount(0)

  await page.getByRole('button', { name: /裁衣/ }).click()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(0)
  await page.getByRole('button', { name: /木工/ }).click()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(1)

  page.once('dialog', (dialog) => dialog.accept())
  await page.getByTestId('clear-all').click()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.saved-recipes > li')).toHaveCount(0)
})
